version: 0.0
os: linux
files:
  - source: frontend/dist/
    destination: /var/www/frontend/
  - source: backend/build/libs/*.jar
    destination: /home/ec2-user/backend/

hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user