# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       # Node.js는 React 빌드용
#       nodejs: 18
#       java: corretto17
#     commands:
#       - echo "Installing dependencies for frontend and backend"
#       - cd frontend
#       - npm ci
#       - cd ..
#   pre_build:
#     commands:
#       - echo "Pre-build started"
#   build:
#     commands:
#       - echo "Building frontend"
#       - cd frontend
#       - npm run build
#       - cd ..

#       - echo "Building backend"
#       - cd backend
#       - chmod +x gradlew
#       - ./gradlew clean build -x test

#       - cd $CODEBUILD_SRC_DIR
#       - echo "Set execute permission for scripts"
#       - chmod +x scripts/*.sh

#   post_build:
#     commands:
#       - echo "Build completed for both frontend and backend"

# artifacts:
#   files:
#     - appspec.yml
#     - scripts/**/*
#     - frontend/dist/**/*
#     - backend/target/*.jar

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - echo "Installing dependencies for frontend and backend"
      - cd frontend
      - npm ci
      - cd ..
  pre_build:
    commands:
      - echo "Pre-build started"
  build:
    commands:
      - echo "Building frontend"
      - cd frontend
      - npm run build
      - cd ..
      - echo "Building backend"
      - cd backend
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - cd $CODEBUILD_SRC_DIR
      - echo "Set execute permission for scripts"
      - chmod +x scripts/*.sh
      - echo "Saving backend JAR name"
      - BACKEND_JAR=$(ls backend/build/libs/*.jar | xargs -n 1 basename)
      - echo $BACKEND_JAR > scripts/backend-jar-name.txt

  post_build:
    commands:
      - echo "Build completed for both frontend and backend"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - scripts/backend-jar-name.txt
    - frontend/dist/**/*
    - backend/build/libs/*.jar